/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package slither;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    App app = new App();
    
    @Test void testApp() {
        assertTrue(true);
    }
}
