/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package slither;

import GUI.Window;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application{

    @Override
    public void start(Stage primaryStage){
        Window window = new Window(primaryStage);
        
        primaryStage.setTitle("Slither");
        primaryStage.setScene(window.getScene());
        primaryStage.show();
        primaryStage.setOnCloseRequest(e -> {
            primaryStage.close();
        });
    }

    public static void main(String[] args) {
        launch(args);
    }
    /*
     * Différencier les foods
     * Food emppoisonnée
     * Commencer Le réseau 
     * Mode a online où le joueur est unique et au centre
     */
    
}