/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package slither;

public class App {
    

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI.Window();
            }
        }); 
    }
}
